version: '3.8'
services:
  jenkins:
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_TLS_VERIFY=""
    image: jenkins/jenkins:lts-jdk17
    networks:
      - jenkins-network
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
    volumes:
      - jenkins_data:/var/jenkins_home

  socat:
    container_name: jenkins-docker
    image: alpine/socat
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
    expose:
      - "2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock

networks:
  jenkins-network:
    name: jenkins

volumes:
  jenkins_data:
